version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: wmenu
    path: .github/config/wmenu.dict
    addWords: true
dictionaries:
  - wmenu
words: []
ignoreWords: []
import: []
enabled: true
enableFiletypes:
  - c
  - cpp
  - bat
